# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Shipwick.Shipwick
PackageVersion: 0.4.1
InstallerType: portable
Commands:
- shipwick
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/shipwick/shipwick/releases/download/v0.4.1/shipwick_windows_amd64.exe
  InstallerSha256: 7EC60FE9441EC4CD9103B7766775CC60EBE8FEC8C16DECB14AB3E5142D892DDB
ManifestType: installer
ManifestVersion: 1.10.0
